# Generated by Django 3.0.3 on 2020-04-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diler',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site', models.URLField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vegan_app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('barcode', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('variety', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FabricProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vegan_app.Fabric')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegan_app.Fruit')),
            ],
            options={
                'unique_together': {('fruit', 'fabric')},
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('diler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegan_app.Diler')),
                ('fabric_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vegan_app.FabricProduct')),
            ],
            options={
                'unique_together': {('diler', 'fabric_product')},
            },
        ),
    ]
